### ISSUE TITLE
autosuggestion pattern and/or tree pattern look up strategy 

### ISSUE THREAD

**Issue by olyanicolaeva** [swiss-art-research-net/performing-arts-ch-templates#1]
**Description:**

Open-source version of Mph does not support the commercial look up strategy; field definitions have to be tested (all templates under "Create Entity" tab).

In some cases the **lookup strategy is referenced in the query** for field definitions and has to be replaced with **bds:search**. 

- For autosuggestion pattern:
`SELECT ?value ?label WHERE {
   ?value a crm:E53_Place ;
  		rdfs:label ?label .
  	?label bds:search ?__token__ ;
        bds:relevance ?score ; 
        bds:matchAllTerms "true"
} LIMIT 100`

- for tree pattern:
`?item a crm:E53_Place ;
  		rdfs:label ?label .
  	?label bds:search ?__token__ ;
        bds:relevance ?score ; 
        bds:matchAllTerms "true"`

In other cases look up strategy is not referenced in the query, however, the template will still produce an error.

**Actions:**

- create a list of  field definitions, where the error appears/does not appear 
- fix the queries based on the example above or in the commit faa9afe6142e36ef88fdc6f32bf12e00a07bd460

**Comment by olyanicolaeva** [comment]
List of templates and fields:
- sapa:createGroup (Genre -autosuggest-; Typ -autosuggest-) 

1. http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/GroupGenre -done
2. http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/GroupType -done

- sapa:createRecordSet (Language -autosuggest-) 
1. http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/RecordResourceLanguage -done, query changed
- sapa:createRecord (Language -autosuggest- Documentary form -autosuggest- ) 
1. http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/RecordResourceLanguage -done
2.  http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/RecordDocumentaryForm - **query needs to be changed still !!!** also for RecordSet
- sapa:createPlace (Surrounding place -autosuggest-) 
1. http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/PlaceFallsWithin - done, query changed 
- sapa:createArchivalPlace (Parent -autosuggest-) 
1. http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/ArchivalPlaceParent - done
- sapa:createInstantiationPhysical (Carrier type -autosuggest-; Record(part) -autosuggest-; Material -autosuggest-; Video damage -autosuggest-)
1.  http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/InstantiationCarrierType - done
2.  http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/InstantiationRecord -done
3. http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/InstantiationMaterial -done
4.  http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/MediaResourceVideoDamage -done (**would like to double-check type**)
- sapa:createInstantiationVirtual (Carrier type -autosuggest-; Record(part) -autosuggest-)
1.  http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/InstantiationCarrierType - done
2.  http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/InstantiationRecord -done

**Comment by fkraeutli** [comment]
Queries for `http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/RecordDocumentaryForm`:
```
treePatterns:
      type: full
      rootsQuery: 'SELECT DISTINCT ?item ?label ?hasChildren WHERE {
          FILTER(NOT EXISTS { ?item skos:broader ?parent. })
          ?item skos:inScheme spav:df .
          ?item rico:name ?label .
          OPTIONAL { ?child skos:broader ?item. }
          BIND(BOUND(?child) AS ?hasChildren)
        }
        ORDER BY (?label)'
      childrenQuery: 'SELECT DISTINCT ?item ?label ?hasChildren WHERE {
          ?item skos:broader ?parent;
            skos:inScheme spav:df .
          ?item rico:name ?label .
          OPTIONAL { ?child skos:broader ?item. }
          BIND(BOUND(?child) AS ?hasChildren)
        }
        ORDER BY (?label)'
      parentsQuery: 'SELECT DISTINCT ?item ?parent ?parentLabel WHERE {
        ?item skos:broader ?parent ;
          skos:inScheme spav:df .
        ?item skos:broader ?parent.
        ?parent (rdfs:label|skos:prefLabel|rdf:value|dc:title|rico:name|rico:identifier) ?parentLabel.
      }'
      searchQuery: 'SELECT DISTINCT ?item ?label ?score ?hasChildren WHERE {
        ?item skos:inScheme spav:df .
        ?item rico:name ?label .
          ?label bds:search ?__token__ ; 
          bds:relevance ?score ; 		 	 
          bds:matchAllTerms "true"
        OPTIONAL { ?child skos:broader ?item. }
        BIND(BOUND(?child) AS ?hasChildren)
      }
      ORDER BY DESC (?score) (?label)
      LIMIT 200
      '
```

**Comment by fkraeutli** [comment]
`http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/MediaResourceVideoDamage` looks good!

**Comment by fkraeutli** [comment]
`http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/InstantiationRecord`

Autosuggestion should be:
```
SELECT $value $label WHERE {
          VALUES (?type ?type_label) {
            (rico:Record " (Record)")
            (rico:RecordPart " (Record Part)")
          }
          $value rico:name ?name .
          ?name bds:search ?__token__ ; 
            bds:relevance ?score ; 
            bds:matchAllTerms "true" 
          OPTIONAL {
            $value rico:identifier ?identifier .
          }
          BIND(CONCAT(IF(BOUND(?identifier), CONCAT(?identifier, ": "), ""), ?name, ?type_label) AS ?label)
      }
```

**Comment by olyanicolaeva** [comment]
@fkraeutli Could you share with me Autosuggestion pattern of this: http://performing-arts.ch/ldp-assets/fieldDefinitionContainer/RecordDocumentaryForm from your local setup?

Thanks!

The rest I have fixed already on the testing instance.

**Comment by fkraeutli** [comment]
Sure thing, you can find it here: https://github.com/swiss-art-research-net/performing-arts-ch-templates/blob/b250e9fb2ead23bdd2b773d78807f797ed755cbd/src/fieldDefinitions.yml#L2426

**Comment by olyanicolaeva** [comment]
@fkraeutli I have fixed the RecordDocumentaryForm too. Could you just double-check for me that RecordDocumentaryForm and RecordSetDocumentaryForm are the same thing? Thanks!

**Comment by fkraeutli** [comment]
> @fkraeutli I have fixed the RecordDocumentaryForm too. Could you just double-check for me that RecordDocumentaryForm and RecordSetDocumentaryForm are the same thing? Thanks!

Looks like it is to me. Maybe something we should ask SAPA.
